"""Add avatar_url to users

Revision ID: 1368347c4c0c
Revises: ba4c3cf6906d
Create Date: 2024-08-15 10:54:38.298900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1368347c4c0c'
down_revision: Union[str, None] = 'ba4c3cf6906d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
